# Generated by Django 4.1.1 on 2022-09-06 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetsBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'budgets_balance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetsCategory',
            fields=[
                ('category_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'budgets categories',
                'db_table': 'budgets_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetsExpenditure',
            fields=[
                ('expenditure_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expenditure_amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('expenditure_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'budgets_expenditure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetsMonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'budgets_monthly_goal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetsPeriod',
            fields=[
                ('period_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
            ],
            options={
                'db_table': 'budgets_period',
                'managed': False,
            },
        ),
    ]
