# Generated by Django 4.1 on 2022-08-25 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetsCategory',
            fields=[
                ('category_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'budgets_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetsExpenditure',
            fields=[
                ('expenditure_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expenditure_amount', models.FloatField()),
                ('expenditure_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'budgets_expenditure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetsPeriod',
            fields=[
                ('period_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
            ],
            options={
                'db_table': 'budgets_period',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetsSaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'budgets_saver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetsBalance',
            fields=[
                ('amount', models.FloatField()),
                ('id_budgets_saver', models.OneToOneField(db_column='id_budgets_saver', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='budgets.budgetssaver')),
            ],
            options={
                'db_table': 'budgets_balance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetsMonthlyGoal',
            fields=[
                ('goal', models.FloatField()),
                ('id_budgets_saver', models.OneToOneField(db_column='id_budgets_saver', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='budgets.budgetssaver')),
            ],
            options={
                'db_table': 'budgets_monthly_goal',
                'managed': False,
            },
        ),
    ]
