

-- object: public.budgets_saver | type: TABLE --
-- DROP TABLE IF EXISTS public.budgets_saver CASCADE;

CREATE TABLE IF NOT EXISTS public.budgets_saver
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE  9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    CONSTRAINT budgets_saver_pkey PRIMARY KEY (id),
    CONSTRAINT budgets_saver_user_id_key UNIQUE (user_id),
    CONSTRAINT budgets_saver_user_id_e96475b4_fk_auth_user_id FOREIGN KEY (user_id)
        REFERENCES public.auth_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
);


-- ddl-end --
ALTER TABLE public.budgets_saver OWNER TO postgres;
-- ddl-end --

-- object: public.budgets_category | type: TABLE --
-- DROP TABLE IF EXISTS public.budgets_category CASCADE;

CREATE TABLE IF NOT EXISTS public.budgets_category
(
    category_id smallint  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223 CACHE 1 ),

    category_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT budgets_category_pkey PRIMARY KEY (category_id)
);

-- ddl-end --
ALTER TABLE public.budgets_category OWNER TO postgres;
-- ddl-end --

-- object: public.budgets_monthly_goal | type: TABLE --
-- DROP TABLE IF EXISTS public.budgets_monthly_goal CASCADE;
CREATE TABLE public.budgets_monthly_goal (
	goal float NOT NULL,
	category_id_budgets_category smallint NOT NULL,
	period_id_budgets_period integer NOT NULL,
	id_budgets_saver bigint NOT NULL,
	CONSTRAINT budgets_monthly_goal_pk PRIMARY KEY (id_budgets_saver,category_id_budgets_category,period_id_budgets_period)

);
-- ddl-end --
ALTER TABLE public.budgets_monthly_goal OWNER TO postgres;
-- ddl-end --

-- object: public.budgets_balance | type: TABLE --
-- DROP TABLE IF EXISTS public.budgets_balance CASCADE;
CREATE TABLE public.budgets_balance (
	amount float NOT NULL,
	period_id_budgets_period integer NOT NULL,
	id_budgets_saver bigint NOT NULL,
	CONSTRAINT budgets_balance_pk PRIMARY KEY (id_budgets_saver,period_id_budgets_period)

);
-- ddl-end --
ALTER TABLE public.budgets_balance OWNER TO postgres;
-- ddl-end --

-- object: public.budgets_expenditure | type: TABLE --
-- DROP TABLE IF EXISTS public.budgets_expenditure CASCADE;
CREATE TABLE public.budgets_expenditure (
	expenditure_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
	expenditure_amount float NOT NULL,
	expenditure_date date NOT NULL,
	description varchar(300),
	category_id_budgets_category smallint NOT NULL,
	id_budgets_saver bigint NOT NULL,
	CONSTRAINT "EXPENDITURE_pk" PRIMARY KEY (expenditure_id)

);
-- ddl-end --
ALTER TABLE public.budgets_expenditure OWNER TO postgres;
-- ddl-end --

-- object: public.budgets_period | type: TABLE --
-- DROP TABLE IF EXISTS public.budgets_period CASCADE;
CREATE TABLE public.budgets_period (
	period_id integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	name varchar(30) NOT NULL,
	start_day date NOT NULL,
	end_day date NOT NULL,
	id_budgets_saver bigint NOT NULL,
	CONSTRAINT "PERIOD_pk" PRIMARY KEY (period_id)

);
-- ddl-end --
ALTER TABLE public.budgets_period OWNER TO postgres;
-- ddl-end --

-- object: budgets_saver_fk | type: CONSTRAINT --
-- ALTER TABLE public.budgets_expenditure DROP CONSTRAINT IF EXISTS budgets_saver_fk CASCADE;
ALTER TABLE public.budgets_expenditure ADD CONSTRAINT budgets_saver_fk FOREIGN KEY (id_budgets_saver)
REFERENCES public.budgets_saver (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: budgets_saver_fk | type: CONSTRAINT --
-- ALTER TABLE public.budgets_monthly_goal DROP CONSTRAINT IF EXISTS budgets_saver_fk CASCADE;
ALTER TABLE public.budgets_monthly_goal ADD CONSTRAINT budgets_saver_fk FOREIGN KEY (id_budgets_saver)
REFERENCES public.budgets_saver (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: budgets_saver_fk | type: CONSTRAINT --
-- ALTER TABLE public.budgets_balance DROP CONSTRAINT IF EXISTS budgets_saver_fk CASCADE;
ALTER TABLE public.budgets_balance ADD CONSTRAINT budgets_saver_fk FOREIGN KEY (id_budgets_saver)
REFERENCES public.budgets_saver (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: budgets_period_fk | type: CONSTRAINT --
-- ALTER TABLE public.budgets_balance DROP CONSTRAINT IF EXISTS budgets_period_fk CASCADE;
ALTER TABLE public.budgets_balance ADD CONSTRAINT budgets_period_fk FOREIGN KEY (period_id_budgets_period)
REFERENCES public.budgets_period (period_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: budgets_category_fk | type: CONSTRAINT --
-- ALTER TABLE public.budgets_expenditure DROP CONSTRAINT IF EXISTS budgets_category_fk CASCADE;
ALTER TABLE public.budgets_expenditure ADD CONSTRAINT budgets_category_fk FOREIGN KEY (category_id_budgets_category)
REFERENCES public.budgets_category (category_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: budgets_category_fk | type: CONSTRAINT --
-- ALTER TABLE public.budgets_monthly_goal DROP CONSTRAINT IF EXISTS budgets_category_fk CASCADE;
ALTER TABLE public.budgets_monthly_goal ADD CONSTRAINT budgets_category_fk FOREIGN KEY (category_id_budgets_category)
REFERENCES public.budgets_category (category_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: budgets_saver_fk | type: CONSTRAINT --
-- ALTER TABLE public.budgets_period DROP CONSTRAINT IF EXISTS budgets_saver_fk CASCADE;
ALTER TABLE public.budgets_period ADD CONSTRAINT budgets_saver_fk FOREIGN KEY (id_budgets_saver)
REFERENCES public.budgets_saver (id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

-- object: budgets_period_fk | type: CONSTRAINT --
-- ALTER TABLE public.budgets_monthly_goal DROP CONSTRAINT IF EXISTS budgets_period_fk CASCADE;
ALTER TABLE public.budgets_monthly_goal ADD CONSTRAINT budgets_period_fk FOREIGN KEY (period_id_budgets_period)
REFERENCES public.budgets_period (period_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
-- ddl-end --

alter table budgets_expenditure drop CONSTRAINT expenditure_nonnegative;
alter table budgets_expenditure add constraint expenditure_nonnegative check(expenditure_amount >= 0);

